version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    environment:
      API_KEY: ${API_KEY}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    depends_on:
      - db
    ports:
      - "8080:8080"

  cloudpub:
    image: cloudpub/cloudpub:latest
    environment:
      TOKEN: ${CLOUDPUB_TOKEN}
    volumes:
      - cloudpub-config:/home/cloudpub
    command: publish http host.docker.internal:8080
#    network_mode: "host"
    depends_on:
      - app

volumes:
  pgdata:
  cloudpub-config:
